export const PkData = [
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fseries%2Ffallout-2023%2Ffallout-2023-poster-small.jpg&w=64&q=75",
    title: "Fallout",
    rate: "8.6",
    season: "1",
    show: "TvShow",
    year: "2024",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fseries%2Fmr-mrs-smith-2023%2Fmr-mrs-smith-2023-poster-small.jpg&w=64&q=75",
    title: "Mr. & Mrs. Smith",
    rate: "7",
    season: "1",
    show: "TvShow",
    year: "2024",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fmovies%2Fricky-stanicky-2023%2Fricky-stanicky-2023-poster-small.jpg&w=64&q=75",
    title: "Ricky Stanicky",
    rate: "6.2",
    season: "1",
    show: "Movie",
    year: "2024",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fmovies%2Fsaltburn-2023%2Fsaltburn-2023-poster-small.jpg&w=64&q=75",
    title: "Saltburn",
    rate: "7",
    season: "1",
    show: "Movie",
    year: "2023",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fseries%2Ffallout-2023%2Ffallout-2023-poster-small.jpg&w=64&q=75",
    title: "Road House",
    rate: "6.2",
    season: "2",
    show: "Movie",
    year: "2024",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fseries%2Fdeath-s-game-2023%2Fdeath-s-game-2023-poster-small.jpg&w=64&q=75",
    title: "Death's Game",
    rate: "8.6",
    season: "1",
    show: "TvShow",
    year: "2023",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fmovies%2Frole-play-2023%2Frole-play-2023-poster-small.jpg&w=64&q=75",
    title: "Role Play",
    rate: "5.5",
    season: "1",
    show: "Movie",
    year: "2024",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fseries%2Findian-police-force%2Findian-police-force-poster-small.jpg&w=64&q=75",
    title: "Indian Police Force",
    rate: "5.2",
    season: "1",
    show: "TvShow",
    year: "2024",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fseries%2Fhazbin-hotel-2019%2Fhazbin-hotel-2019-poster-small.jpg&w=64&q=75",
    title: "Hazbin Hotel",
    rate: "7.8",
    season: "2",
    show: "Tv season",
    year: "2019",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fseries%2Fexpats-2023%2Fexpats-2023-poster-small.jpg&w=64&q=75",
    title: "Expats",
    rate: "6.2",
    season: "1",
    show: "Tv season",
    year: "2023",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fmovies%2Fupgraded-2023%2Fupgraded-2023-poster-small.jpg&w=64&q=75",
    title: "Upgraded",
    rate: "6.1",
    season: "1",
    show: "Movie",
    year: "2024",
  },
  {
    img: "https://similarwatch.com/_next/image/?url=https%3A%2F%2Fmovies.imgcdn.org%2Fseries%2Ffallout-2023%2Ffallout-2023-poster-small.jpg&w=64&q=75",
    title: "This Is Me...Now",
    rate: "4.4",
    season: "1",
    show: "Movie",
    year: "2024",
  },
];
